/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface P01Report {
  summary?: string;
  verdict: "suspicious" | "benign" | "unclear";
  confidence: number;
  facts: {
    text: string;
    evidence: {
      line: number;
      text: string;
    }[];
  }[];
  open_questions?: string[];
  model: string;
}
