# generated by datamodel-codegen:
#   filename:  alert.created.schema.json

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel


class AlertCreated(BaseModel):
    alert_id: UUID
    number: int
    source: str
    labels: dict[str, str]
    filename: str | None = None
    received_at: datetime
    text: str
