# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Correlation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    alert_id: UUID
    run_id: UUID | None = None
    task_id: UUID | None = None


class Envelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    message_id: UUID
    type: str
    occurred_at: datetime
    correlation: Correlation
    payload: dict[str, Any]
