# generated by datamodel-codegen:
#   filename:  p01_ai_validation.input.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class P01Input(BaseModel):
    lines: list[str] = Field(..., min_length=1)
