# generated by datamodel-codegen:
#   filename:  p01_ai_validation.output.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, confloat, conint


class EvidenceItem(BaseModel):
    line: conint(ge=1)
    text: str


class Fact(BaseModel):
    text: str
    evidence: list[EvidenceItem]


class P01Report(BaseModel):
    summary: str | None = None
    verdict: Literal['suspicious', 'benign', 'unclear']
    confidence: confloat(ge=0.0, le=1.0)
    facts: list[Fact]
    open_questions: list[str] | None = None
    model: str
