# generated by datamodel-codegen:
#   filename:  task.playbook.schema.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel


class TaskPlaybook(BaseModel):
    task_id: UUID
    run_id: UUID
    alert_id: UUID
    playbook: str
    input: dict[str, Any]
