/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Envelope {
  v: 1;
  message_id: string;
  type: string;
  occurred_at: string;
  correlation: {
    alert_id: string;
    run_id?: string | null;
    task_id?: string | null;
  };
  payload: {};
}
