/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AlertCreated {
  alert_id: string;
  number: number;
  source: string;
  labels: {
    [k: string]: string;
  };
  filename?: string | null;
  received_at: string;
  text: string;
}
