/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TaskPlaybook {
  task_id: string;
  run_id: string;
  alert_id: string;
  playbook: string;
  input: {};
}
